name: New Command
description: Create a feature request for a new command
labels: ["feature request", "new command", "triage required"]
body:
  - type: markdown
    id: intro-md
    attributes:
      value: |
        Thank you for taking the time to fill out this feature report for a new command!
  - type: textarea
    attributes:
      label: "Summarize Functionality"
      description: "Please provide a clear/concise description of what problem the new command will solve."
    validations:
      required: true
  - type: dropdown
    id: existing-command
    attributes:
      label: "Is this a wrapper command that will utilize current commands already in the module?"
      options:
        - "Yes"
        - "No"
    validations:
      required: false
  - type: dropdown
    id: api-endpoint
    attributes:
      label: "Is this a command based on a SQL Server SMO?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: api-endpoint
    attributes:
      label: "Is this a command based on a SQL Server T-SQL?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: version-specific
    attributes:
      label: "Is the command/functionality only available in specific version of SQL Server or in Azure SQL DB"
      description: "If so please indicate what version of SQL Server in the Technical Details."
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Technical Details"
      description: "Provide as much detail on functionality of the command, links to code examples, screenshots, or write-ups of the desired functionality."
    validations:
      required: false